//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myFihrist {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class ProgramAyar : global::System.Configuration.ApplicationSettingsBase {
        
        private static ProgramAyar defaultInstance = ((ProgramAyar)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ProgramAyar())));
        
        public static ProgramAyar Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ilkKurulum {
            get {
                return ((bool)(this["ilkKurulum"]));
            }
            set {
                this["ilkKurulum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string veriYolu {
            get {
                return ((string)(this["veriYolu"]));
            }
            set {
                this["veriYolu"] = value;
            }
        }
    }
}
